---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->
<!-- `devtools::build_readme()` -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# GHCNr

<!-- badges: start -->
<!-- badges: end -->

```{r}
library(terra)
library(GHCNr)

world <- vect("~/shapefiles/europe/CNTR_BN_10M_2020_3857.shp") |>
  project("EPSG:4326")
germany <- world[world$CNTR_CODE == "DE", ]
roi <- ext(germany)
roi <- as.polygons(roi, crs = crs(germany))

# roi <- ext(9.5, 15, 41, 45)
# roi <- crop(world, roi)
s <- stations(roi, show = TRUE)
s <- s[s$dataType == "TMAX", ]
s <- crop(s, germany)  # should be mask(), but shapefile is line.

d <- daily(s$id[1:5], "1974-01-01", "2023-12-31")
daily_coverage(d)
with(
  subset(d, station == unique(d$station)[1]),
  plot(
    date,
    tmax / 10,
    col = "violet",
    type = "l",
    frame = FALSE,
    xlab = "Date",
    ylab = "Maximum temperature"
  )
)
with(
  subset(d, station == unique(d$station)[2]),
  lines(date, tmax / 10, col = "tomato2")
)
with(
  subset(d, station == unique(d$station)[3]),
  lines(date, tmax / 10, col = "gold2")
)
with(
  subset(d, station == unique(d$station)[4]),
  lines(date, tmax / 10, col = "green2")
)
with(
  subset(d, station == unique(d$station)[5]),
  lines(date, tmax / 10, col = "blue")
)
```

# focus on 3 stations only
points(
  s[7:9],
  col = "grey20", bg = c("violet", "tomato2", "gold"),
  pch = 23, cex = 2
)
d <- daily(unique(s$id)[7:9], "1974-01-01", "2023-12-31")
daily_coverage(d)
with(
  subset(d, station == unique(d$station)[1]),
  plot(
    date,
    tmax / 10,
    col = "violet",
    type = "l",
    frame = FALSE,
    xlab = "Date",
    ylab = "Maximum temperature"
  )
)
with(
  subset(d, station == unique(d$station)[2]),
  lines(date, tmax / 10, col = "tomato2")
)
with(
  subset(d, station == unique(d$station)[3]),
  lines(date, tmax / 10, col = "gold2")
)
```